'use client'

import { WatchlistAnalyzer } from '@/components/watchlist-analyzer'
import { ThemesAndSectors } from '@/components/themes-and-sectors'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { BarChart3, AlertTriangle, ArrowLeft } from 'lucide-react'
import Link from 'next/link'

export default function WatchlistPage() {
  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b border-border">
        <div className="container mx-auto px-4 py-6">
          <div className="flex items-center justify-between mb-2">
            <div className="flex items-center gap-3">
              <Link href="/">
                <Button variant="ghost" size="sm" className="gap-2 -ml-2">
                  <ArrowLeft className="w-4 h-4" />
                  Back
                </Button>
              </Link>
              <div className="p-2 bg-primary rounded-lg">
                <BarChart3 className="w-6 h-6 text-primary-foreground" />
              </div>
              <div>
                <h1 className="text-2xl font-bold">Watchlist Analyzer</h1>
                <p className="text-sm text-muted-foreground">Ranked trading signals from your watchlist</p>
              </div>
            </div>
            <Badge variant="outline" className="bg-amber-500/10 text-amber-600 border-amber-500/20">
              <AlertTriangle className="w-3 h-3 mr-1" />
              Paper Trading Only
            </Badge>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="container mx-auto px-4 py-8">
        <div className="max-w-5xl mx-auto">
          <WatchlistAnalyzer />

          {/* Info Section */}
          <div className="mt-12 grid gap-4 md:grid-cols-3">
            <div className="p-4 bg-muted/50 rounded-lg">
              <h3 className="font-semibold text-sm mb-2">How It Works</h3>
              <p className="text-xs text-muted-foreground">
                Paste your watchlist JSON with market data. The AI analyzes each ticker and returns the best trading signals ranked by action type, risk/reward, and confidence.
              </p>
            </div>
            <div className="p-4 bg-muted/50 rounded-lg">
              <h3 className="font-semibold text-sm mb-2">Quality Filter</h3>
              <p className="text-xs text-muted-foreground">
                Only signals with strong setups are returned. Risk/reward must be 2.0+, confidence 60%+. NO TRADE signals included only when relevant.
              </p>
            </div>
            <div className="p-4 bg-muted/50 rounded-lg">
              <h3 className="font-semibold text-sm mb-2">Best Practices</h3>
              <p className="text-xs text-muted-foreground">
                Include technical indicators (RSI, EMAs, VWAP, ATR) and support/resistance levels. More quality data produces better signals.
              </p>
            </div>
          </div>

          {/* Disclaimer */}
          <div className="mt-12 p-4 bg-muted/30 rounded-lg border border-border">
            <p className="text-xs text-muted-foreground text-center">
              <strong className="text-foreground/60">Disclaimer:</strong> This tool is for paper trading and educational purposes only.
              Trading signals are generated by AI and should not be considered financial advice.
              Always do your own research before making any trading decisions.
            </p>
          </div>
        </div>

        {/* Themes & Sectors Section */}
        <div className="max-w-7xl mx-auto mt-16 pb-16">
          <ThemesAndSectors />
        </div>
      </main>
    </div>
  )
}

